### ISSUE TITLE
including bfruntime.proto file

### ISSUE THREAD

**Issue by ralfkundel** [barefootnetworks/Open-Tofino#10]
Hi,
it would be great if the **bfruntime.proto** file would be open sourced as well in this repository. By that, control plane apps can be programmed in any language, i.e. in our case Golang and Python, and open sourced. As the C header files for the API are already in this reposity, I don't assume any new confidential content in there.

Our current workaround (which is very ugly) is: 1. we provide the Golang/Python code without the bfruntime.proto file, 2. the user has to find the proto file in the sde and copy it into the project and 3. compile the proto file with the protobuf compiler by himself.
--> This would be much easier if the proto file is public available.

best,
Ralf

**Comment by vgurevich** [comment]
Hello Ralf,

I agree, we should add this file to the repo. We'll do that in the next update.

Thanks,
Vladimir

**Comment by CommitThis** [comment]
Hi @vgurevich, is there any update on this?

**Comment by vgurevich** [comment]
We will update the repo shortly after SDE-9.7.0 release and we'll take care of that.

**Comment by ralfkundel** [comment]
Hi @vgurevich,
anything new on this (as 9.7.0 is already out for more than a month)?

best and thanks,

**Comment by vgurevich** [comment]
Sorry for the delay. @shikumar1 and I working on it.

**Comment by vgurevich** [comment]
The latest repository update contains [bftuntime.proto](https://github.com/barefootnetworks/Open-Tofino/blob/master/share/bf_rt_shared/proto/bfruntime.proto)
