### ISSUE TITLE
How many TCAM entries are consumed by one range？

### ISSUE THREAD

**Issue by zhou121** [barefootnetworks/Open-Tofino#15]
Please be aware that the implementation of range match consumes multiple TCAM entries per range entry and refer to the documentation for details.

How many TCAM entries are consumed by one range？ 
Where can the documentation be found?

**Comment by ederollora** [comment]
Hi,

I believe this question might fit better the Intel Connectivity Education Hub. Have you tried the Intel forum in the Hub? You can check the Hub [here](https://www.intel.la/content/www/xl/es/products/network-io/programmable-ethernet-switch/connectivity-education-hub/overview.html).

In general terms, I believe that the TCAM entries consumed depends on the exact type of range (i.e. range expression). If you mention your particular case in the forum I am sure they can help you on that.

Cheers,

**Comment by vgurevich** [comment]
@zhou121 -- while the functionality of the `range` match kind is open (as well as the interface from the Barefoot Runtime Interface perspective), the actual details of target implementation are not publicly available yet.

Please, follow @ederollora 's advice above if you need more information.
