### ISSUE TITLE
"tna_32q_2pipe" for 2 pipes switch

### ISSUE THREAD

**Issue by huzlee** [barefootnetworks/Open-Tofino#16]
Hi,
I'm trying to run the example "tna_32q_2pipe" and when I execute the ```./run_switchd.sh --arch tofino -p tna_32q_2pipe``` I get some errors:
```
2022-03-03 21:55:27.055651 BF_DVM ERROR - Program "tna_32q_2pipe" Pipeline "pipeline_profile_a" cannot be assigned to device 0 pipe 2, only 2 pipe(s) available
2022-03-03 21:55:27.055722 BF_DVM ERROR - Program "tna_32q_2pipe" Pipeline "pipeline_profile_b" cannot be assigned to device 0 pipe 3, only 2 pipe(s) available
ERROR: bf_device_add failed(3) for dev_id 0
ERROR: bf_switchd_device_add failed(3) for dev_id 0
```
and there are no ports to show up 
```
bf-sde.pm> show -a
-----+---2022-03-03 21:53:37.775510 BF_PM ERROR - pm_port_info_get_first:191 Unable to get first port info for dev : 0, port_key 140474654489680 : map_err : 2
-+---+----+-------+----+---+---+---+--------+----------------+----------------+-
PORT |MAC |D_P|P/PT|SPEED  |FEC |RDY|ADM|OPR|LPBK    |FRAMES RX       |FRAMES TX       |E
-----+----+---+----+-------+----+---+---+---+--------+----------------+----------------+-
```
I'd like to know how to fix this problem？Thanks😊

**Comment by vgurevich** [comment]
@huzlee -- the purpose of this repo is to provide the definition of interfaces and some official examples of those.

If you have any issues using the SDE, you need to use standard support channels ([Intel Premier Support (IPS)](http://premiersupport.intel.com/) for the commercial customers and [Intel Connectivity Research Program](http://intel.com/icrp) [Forum](https://community.intel.com/t5/Intel-Connectivity-Research/bd-p/connectivity-research-programforum-board) for the academic and research organizations)
