### ISSUE TITLE
Can global registers be implemented？

### ISSUE THREAD

**Issue by ghost** [barefootnetworks/Open-Tofino#17]
I want to make _deq_qdepth_ (from _egress_intrinsic_metadata_t_) available in the _SwitchIngress_. So I try to declare a global _Register_, and the **same** register will be used by _RegisterAction_ defined in _SwitchIngress_ and _SwitchEgress_. In this way, the data can be shared between _SwitchIngress_ and _SwitchEgress_.

The p4 code looks like:
```
Register<T, I>(size, initial_value) global_reg;

control SwitchIngress(...) {
    RegisterAction<T, I, U>(global_reg) global_reg_action1 = {...};
    
    apply {
        ...;
        global_reg_action1.execute(idx);
    }
}

control SwitchEgress(...) {
    RegisterAction<T, I, U>(global_reg) global_reg_action2= {...};

    apply {
        ...;
        global_reg_action2.execute(idx);
    }
}
```

However, it seems like impossible to implement. 

I wonder if there is any approach to achieve this "global register"? Thanks a lot.

**Comment by vgurevich** [comment]
@zhma989, The main purpose of this repository is to publish the interfaces, which, in turn, makes it possible for everyone to publish their code. 

For actual development questions, please use [Intel Premier Support](http://premiersupport.intel.com) (if you are a commercial customer) or [Intel Connectivity Research Program Forum](https://community.intel.com/t5/Intel-Connectivity-Research/bd-p/connectivity-research-programforum-board) (if you represent an academic or a research organization)

Also, please note that posting screenshots, logs, etc. produced by the tools violates the NDA. Please, be careful next time.
