### ISSUE TITLE
execute test.py of tna_timestamp, I have some issue

### ISSUE THREAD

**Issue by chocolate0515** [barefootnetworks/Open-Tofino#18]
Execute test.py of nta_timestamp, there are the following issues

root@lanner-control:~/bf-sde-9.5.0# ./run_p4_tests.sh  -p tna_timestamp
Using SDE /root/bf-sde-9.5.0
Using SDE_INSTALL /root/bf-sde-9.5.0/install
Using TEST_DIR /root/bf-sde-9.5.0/pkgsrc/p4-examples/p4_16_programs/tna_timestamp
Using PATH /root/bf-sde-9.5.0/install/bin:/root/bf-sde-9.5.0/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Arch is tofino
Target is asic-model
Using BF_PTF with bf_pktpy.
Setting up veth interfaces
No of Veths is 64
Adding CPU veth
Connecting to localhost port 7777 to check status on these devices: [0]
Waiting for device 0 to be ready
Started port clean script
: <type 'str'>
/root/bf-sde-9.5.0/install/lib/python2.7/site-packages/bf-ptf:/root/bf-sde-9.5.0/install/lib/python2.7/site-packages/p4testutils:/root/bf-sde-9.5.0/install/lib/python2.7/site-packages/tofinopd/:/root/bf-sde-9.5.0/install/lib/python2.7/site-packages/tofino:/root/bf-sde-9.5.0/install/lib/python2.7/site-packages/: <type 'str'>
test.TimestampTest ... Subscribe attempt #1
Subscribe response received 0
Binding with p4_name tna_timestamp
Binding with p4_name tna_timestamp successful!!
Received tna_timestamp on GetForwarding on client 0, device 0
ERROR

======================================================================
ERROR: test.TimestampTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/bf-sde-9.5.0/pkgsrc/p4-examples/p4_16_programs/tna_timestamp/test.py", line 73, in runTest
    nrcv = ipkt.__class__(rcv_pkt)
TypeError: __init__() takes exactly 1 argument (2 given)

----------------------------------------------------------------------
Ran 1 test in 2.203s

FAILED (errors=1)
()
******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!
()
The following tests errored:
TimestampTest
()
******************************************

**Comment by vgurevich** [comment]
@chocolate0515, 

The main purpose of this repository is to publish the interfaces, which, in turn, makes it possible for everyone to publish their code.

For actual development questions, please use [Intel Premier Support](http://premiersupport.intel.com/) (if you are a commercial customer) or [Intel Connectivity Research Program Forum](https://community.intel.com/t5/Intel-Connectivity-Research/bd-p/connectivity-research-programforum-board) (if you represent an academic or a research organization)
