### ISSUE TITLE
SDE9.2.0: use API got "$pre.node : Value 16 is greater than what field size 4 for field id 1 allows" errors

### ISSUE THREAD

**Issue by suitgo** [barefootnetworks/Open-Tofino#22]
When I use the API "BfRtTableKey->setValue" to add entries, when the key value is big then 15, there will throw out the error msg: "$pre.node : Value 16 is greater than what field size 4 for field id 1 allows".
I have checkout that the key size of the table "$pre.node" is 32bits. Why I got this error? How can I add entry for this table correctly?  Or it's bug for the version 9.2.0?

**Comment by vgurevich** [comment]
@suitgo -- please, use the appropriate Intel support forums for all your questions. As explained in the README.md, this repository exists for publishing the interface files only.
