### ISSUE TITLE
register support write operation?

### ISSUE THREAD

**Issue by kphf1995cm** [barefootnetworks/Open-Tofino#5]
Does the register in P4_16 support write opreration ? Could you give an example of register write operation in P4_16?

**Comment by vgurevich** [comment]
The latest versions of TNA and Barefoot compiler support `read()` and `write()` methods for registers. You can find the definitions [right here](https://github.com/barefootnetworks/Open-Tofino/blob/master/share/p4c/p4include/tofino.p4#L617). 

These methods are enough for simple register operations, while the `RegisterAction()` extern allows you to express more advanced processing as well.

For more details and examples I suggest attending [Intel Connectivity Academy](http://intel.com/ica)

**Comment by kphf1995cm** [comment]
Does SDE 8.9.1 support register read and write operations？
--
 况鹏
    Peng Kuang
 清华大学 网络科学与网络空间研究院
    Tel： +86 18292886592
    ***@***.***


发件人: Vladimir Gurevich
发送时间: 2021年5月26日 1:55
收件人: barefootnetworks/Open-Tofino
抄送: echorez; Author
主题: Re: [barefootnetworks/Open-Tofino] register support write operation?(#5)

The latest versions of TNA and Barefoot compiler support read() and write() methods for registers. You can find the definitions right here.
These methods are enough for simple register operations, while the RegisterAction() extern allows you to express more advanced processing as well.
For more details and examples I suggest attending Intel Connectivity Academy

**Comment by kphf1995cm** [comment]
It seems that SDE 8.9.1 does not support register read and write operations？

--
 况鹏
    Peng Kuang
 清华大学 网络科学与网络空间研究院
    Tel： +86 18292886592
    ***@***.***


发件人: Vladimir Gurevich
发送时间: 2021年5月26日 1:55
收件人: barefootnetworks/Open-Tofino
抄送: echorez; Author
主题: Re: [barefootnetworks/Open-Tofino] register support write operation?(#5)

The latest versions of TNA and Barefoot compiler support read() and write() methods for registers. You can find the definitions right here.
These methods are enough for simple register operations, while the RegisterAction() extern allows you to express more advanced processing as well.
For more details and examples I suggest attending Intel Connectivity Academy

**Comment by vgurevich** [comment]
@kphf1995cm -- as stated, this is a relatively new feature and it is not available in the older releases.
