### ISSUE TITLE
P4 Compiler

### ISSUE THREAD

**Issue by drobinkent** [barefootnetworks/Open-Tofino#7]
Is there any P4 compiler available (as open-source) for this switch?

**Comment by vgurevich** [comment]
So far, we only distribute the interfaces (as described in the README).

If you are interested in obtaining Intel P4 Studio SDE:

- If you represent a commercial organization, I would recommend reaching out to barefootsales@intel.com
- If you represent an academic or research organization, consider joining [Intel Connectivity Research Program](http://intel.com/icrp)

**Comment by drobinkent** [comment]
Thanks
