### ISSUE TITLE
deq_timedelta

### ISSUE THREAD

**Issue by Mandorath** [barefootnetworks/Open-Tofino#8]
Hi,

Considering that enq_tstamp/global_timestamp is in ns I would assume the the deq_timedelta also in ns and not us, is this correct?
I can recall something about reading (all)  the timestamps being in ns but I can't seem to find it anymore, so I want to be sure :). I checked the  p4include/tofino.p4 file and and the pdf but I could not find it stated there.
So it would range from 1 ns to approximately 262 us.

**Comment by vgurevich** [comment]
Yes, all Tofino timestamps are in ns.
